const Audio1 = require('./50CentSnare.wav')
const Audio2 = require('./Bass.wav')
const Audio3 = require('./Clap1.wav')
const Audio4 = require('./Clap2.wav')
const Audio5 = require('./Closed-Hi-Hat1.wav')
const Audio6 = require('./Closed-Hi-Hat2.wav')
const Audio7 = require('./Closed-Hi-Hat3.wav')
const Audio8 = require('./Closed-Hi-Hat4.wav')
const Audio12 = require('./Closed-Hi-Hat5.wav')
const Audio9 = require('./D12Snare.wav')
const Audio10 = require('./DreSnare.wav')
const Audio11 = require('./Kick1.wav')
const Audio13 = require('./Kick2.wav')
const Audio14 = require('./Kick3.wav')
const Audio15 = require('./Kick4.wav')
const Audio16 = require('./Kick5.wav')
const Audio17 = require('./Kick6.wav')
const Audio18 = require('./Kick7.wav')
const Audio19 = require('./Open-Hi-Hat1.wav')
const Audio20 = require('./Open-Hi-Hat2.wav')
const Audio21 = require('./Open-Hi-Hat3.wav')
const Audio22 = require('./Open-Hi-Hat4.wav')
const Audio23 = require('./Snare1.wav')
const Audio24 = require('./Snare2.wav')
const Audio25 = require('./Snare3.wav')
const Audio26 = require('./Snare4.wav')
const Audio27 = require('./Snare5.wav')

const drumSamples = [Audio1, Audio2, Audio3, Audio4, Audio5, Audio6, Audio7, Audio8, Audio9, Audio10, Audio11, Audio12, Audio13, Audio14, Audio15, Audio16, Audio17, Audio18, Audio19, Audio20, Audio21, Audio22, Audio23, Audio24, Audio25, Audio26, Audio27]

export default drumSamples
